### ISSUE TITLE
TBK/core/pymodule/tbkpy/test/pong.py   ERROR:  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Umbrella167** [Turing-zero/tbk#1] opened 2024-08-08 14:23 UTC
python  version 3.12 
run TBK/core/pymodule/tbkpy/test/pong.py  and ping.py 

pong.py
ERROR:  Segmentation fault (core dumped)
--------------------------------------------------
  ~/Downloads/TBK$ python3 tbkpy/test/pong.py
  (2024-08-08 20:22:54.162425):param.h(81):testtest - Process
  (2024-08-08 20:22:54.166097):param.h(81):testtest - Localhost
  (2024-08-08 20:22:54.168694):param.h(62):in server cb key: __cl__/_test_pong_Ping_Suber:ping/__v__, value: Localhost
  (2024-08-08 20:22:54.169776):param.h(62):in server cb key: __cl__/_test_pong_Ping_Suber:ping/__t__, value: Enum<CommLevel>
  (2024-08-08 20:22:54.171010):param.h(62):in server cb key: __cl__/_test_pong_Ping_Suber:ping/__i__, value: Manual|Process|Localhost|LocalNetwork
  (2024-08-08 20:22:54.246848):core.cpp(66):SubscriberBase::setSocket : 192.168.31.211:15953
  (2024-08-08 20:22:55.990909):module.cpp(18):SubscriberPy::_cpp_cb
  (2024-08-08 20:22:55.990957):module.cpp(20):convert data : ping
  (2024-08-08 20:22:55.990975):module.cpp(21):convert success
  (2024-08-08 20:22:55.990991):module.cpp(23):SubscriberPy::_cpp_cb calling py_callback,0x710414003bc0,4
  Segmentation fault (core dumped)

**Comment by Mark-tz** [comment] 2024-08-16 05:44
fixed in https://github.com/Turing-zero/TBK/commit/be38f9ffc7a4fb96146878d012da456355a8dd85

which is caused by missing the pybind11::gil_scoped_acquire

**Closed as completed** 2024-08-16 05:45 UTC
Labels: bug
